---
- name: install windows applications
  hosts: windows
  tasks:
    - name: Install 7zip
      win_chocolatey:
        name: 7zip
        state: present
    - name: Install Firefox
      win_chocolatey:
        name: firefox
        state: present
    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present
